image: debian:unstable

before_script:
  - apt-get update -qq
  - apt-get install -y make qemu binfmt-support qemu-user-static

x86-64:
  stage: test
  script:
    - dpkg --add-architecture arm64
    - apt-get update -qq
    - apt-get install -y libc6-dev:amd64 gcc
    - make -C tests test-native

i686:
  stage: test
  script:
    - dpkg --add-architecture i386
    - apt-get update -qq
    - apt-get install -y gcc-i686-linux-gnu libc6-dev-i386-cross libc6:i386
    - make -C tests test-ia32 CC_IA32=i686-linux-gnu-gcc

aarch64:
  stage: test
  script:
    - dpkg --add-architecture arm64
    - apt-get update -qq
    - apt-get install -y gcc-aarch64-linux-gnu libc6-dev-arm64-cross libc6:arm64
    - make -C tests test-aarch64 CC_AARCH64=aarch64-linux-gnu-gcc

armhf:
  stage: test
  script:
    - dpkg --add-architecture armhf
    - apt-get update -qq
    - apt-get install -y gcc-arm-linux-gnueabihf libc6-dev-armhf-cross libc6:armhf
    - make -C tests test-armv7 CC_ARMv7="arm-linux-gnueabihf-gcc -marm"


armhf-thumb:
  stage: test
  script:
    - dpkg --add-architecture armhf
    - apt-get update -qq
    - apt-get install -y gcc-arm-linux-gnueabihf libc6-dev-armhf-cross libc6:armhf
    - make -C tests test-armv7 CC_ARMv7="arm-linux-gnueabihf-gcc -mthumb"


riscv:
  stage: test
  script:
    - dpkg --add-architecture riscv64
    - apt-get update -qq
    - apt-get install -y gcc-riscv64-linux-gnu
    - echo /usr/local/lib/riscv64-linux-gnu   >>/etc/ld.so.conf.d/riscv64-linux-gnu.conf
    - echo /lib/riscv64-linux-gnu             >>/etc/ld.so.conf.d/riscv64-linux-gnu.conf
    - echo /usr/lib/riscv64-linux-gnu         >>/etc/ld.so.conf.d/riscv64-linux-gnu.conf
    - echo /usr/riscv64-linux-gnu/lib         >>/etc/ld.so.conf.d/riscv64-linux-gnu.conf
    - ln -s /usr/riscv64-linux-gnu/lib/ld-linux-riscv64-lp64d.so.1 /lib
    - make -C tests test-riscv CC_RISCV="riscv64-linux-gnu-gcc -static"
